version: "3.9"
services:
  database:
    build: ./database
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  video_uploader:
    env_file:
      - docker.env
    build: ./video_uploader
    ports:
      - "8001:80"
    depends_on:
      database:
        condition: service_healthy