version: "3.9"
services:
  database:
    build: ./database
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  processing_queue:
    image: "rabbitmq:3.7-management-alpine"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "pass"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 5s
      timeout: 5s
      retries: 5
  video_uploader:
    env_file:
      - docker.env
    build: ./video_uploader
    ports:
      - "8001:80"
    depends_on:
      database:
        condition: service_healthy
      processing_queue:
        condition: service_healthy
  ml_classifier:
    env_file:
      - docker.env
    build: ./ml_classifier
    depends_on:
      database:
        condition: service_healthy
      processing_queue:
        condition: service_healthy
  context_mixer:
    env_file:
      - docker.env
    build: ./context_mixer
    ports:
      - "3001:3001"
  frontend:
    build: ./frontent
    ports:
      - "3000:3000"
    depends_on:
      context_mixer:
        condition: service_started